# -*- coding: utf-8 -*-
"""myapikeys.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtoyFG6AkQiNlB46gf83vfahftOTKBb2
"""

#OPENAI_KEY = "sk-XHbxcz6JeONf5_xUjUhpkuHoeAPSyenYNaMBNyZ3z-T3BlbkFJmYhTtY8fSEIOItCmN5m-ERvfqnMIfo9fJsis5uYSwA"
